"""Generate docs/inventory.md and docs/mappings.md from the extraction outputs."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from etl.discover import SOURCE_DIR, all_years, units_for_year
from etl.normalize import norm
from etl.terms import RULES

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "out"
DOCS = ROOT / "docs"

SUBJECTS = [  # (label, domain, keywords in the normalised title)
    ("K-12 students", "k12", ["دانش آموز"]),
    ("K-12 teachers/staff", "k12", ["کارکنان", "معلم"]),
    ("K-12 schools/classes", "k12", ["امکانات", "آموزشگاه", "مدارس", "دبستان", "کلاس"]),
    ("K-12 graduates/passed", "k12", ["فارغ التحصیل", "قبول"]),
    ("HE students", "he", ["دانشجو"]),
    ("HE new entrants", "he", ["ثبت نام", "پذیرفته", "پذیرفه"]),
    ("HE graduates", "he", ["دانش آموخت", "فارغ التحصیل"]),
    ("HE academic staff", "he", ["آموزشگران", "کارکنان آموزشی", "هیات علمی", "استادان", "کادر آموزشی"]),
    ("HE institutions", "he", ["مراکز آموزش عالی", "دانشگاهها و", "تعداد دانشگاه"]),
]


def _subjects(title: str, domain: str) -> list[str]:
    t = norm(title).replace(" ", "")
    return [lab for lab, d, kws in SUBJECTS if d == domain and any(k.replace(" ", "") in t for k in kws)]


def write_inventory() -> None:
    t = pd.read_parquet(OUT / "tables.parquet")
    units = pd.read_parquet(OUT / "units.parquet").set_index("yearbook_sh")
    st = pd.read_parquet(OUT / "table_status.parquet") if (OUT / "table_status.parquet").exists() else None
    if st is not None:
        t = t.merge(st[["source_file", "source_table", "check_status"]], on=["source_file", "source_table"], how="left")
    t["check_status"] = t.get("check_status", pd.Series(dtype=str)).fillna("unchecked")
    L = ["# Inventory of the education chapter, 1345-1402 SH",
         "",
         f"Source root (read-only): `{SOURCE_DIR}`. Generated by `uv run python -m etl.run docs` from the ETL",
         "outputs (`data/out/tables.parquet`), so every statement below is what the parser actually found.",
         "",
         "Legend: **geo** = national (year rows only) / province (>=10 provinces as rows). "
         "**status** = validation of the table's arithmetic (see docs/validation.md).",
         "",
         "## Summary per year",
         "",
         "| year | format (unit) | education file(s) | tables (K-12/HE/other) | province tables | subjects found | tables failing checks |",
         "|---|---|---|---|---|---|---|"]
    detail = []
    for y in all_years():
        us = units_for_year(y)
        kind = units.loc[y, "kind"] if y in units.index else (us[0].kind if us else "none")
        files = sorted({u.rel(p) for u in us for p in u.source_paths})
        ty = t[t.yearbook_sh == y]
        nk, nh = (ty.domain == "k12").sum(), (ty.domain == "he").sum()
        no = len(ty) - nk - nh
        prov = (ty.geo == "province").sum()
        subj = sorted({s for r in ty.itertuples() for s in _subjects(r.title, r.domain)})
        fail = (ty.check_status == "failed").sum()
        fdesc = files[0] if len(files) == 1 else (f"{len(files)} files in `{Path(files[0]).parent}/`" if files else "-")
        if len(files) == 1:
            fdesc = f"`{fdesc}`"
        L.append(f"| {y} | {kind} | {fdesc} | {nk}/{nh}/{no} | {prov} | {', '.join(subj) or '**none parsed**'} | {fail} |")
        if len(ty):
            detail.append(f"\n### {y}\n")
            detail.append("| table | domain | geo | rows x cols | status | title |\n|---|---|---|---|---|---|")
            for r in ty.sort_values("source_table").itertuples():
                if r.domain in ("k12", "he", "teacher_training"):
                    title = r.title.replace("|", "/")[:110]
                    detail.append(f"| {r.source_table} | {r.domain} | {r.geo} | {r.n_rows}x{r.n_cols} | {r.check_status} | {title} |")
    L += ["", "## Gaps and caveats (read this before using a year)", "", GAPS, "", "## Tables per year", ""]
    L += detail
    (DOCS / "inventory.md").write_text("\n".join(L) + "\n")


GAPS = """\
* **1354** has no folder in the source tree (the yearbook series skips it here).
* **1370-1375 and part of 1379**: education tables are Word-exported HTML whose tables are *plain
  text* (ASCII-art with the letter «ا» as column rule) — not parsed yet (`etl/extract/plaintext.py`).
  National figures for these years are still available through the historic rows that later
  yearbooks (1380, 1381, ...) reprint (e.g. 1370, 1375-1379 rows of the 1380 yearbook).
* **1376-1378**: one PDF per table, but the PDFs use a legacy non-Unicode Persian font: the text
  layer is garbage (digits included). Needs OCR (docling/tesseract) — not done. Same fallback as above.
* **1345-1369** (whole-book `.doc`, converted with LibreOffice): tables are extracted, but their
  layouts differ (orientation, units such as «هزار نفر», section rows) and were **not verified**;
  the analytic views therefore only use yearbooks >= 1380. **1360**: the education chapter was not
  located by the chapter-segmentation heuristic.
* **1387** ships per-chapter `.doc` files whose tables are nested inside layout tables; handled.
* **1399-1402** are PDFs: headers are taken from the matching Word-era table (1393-1398) and
  checked by value agreement and arithmetic; `header_source` records the template. 1399's
  province tables are split across pages differently and several of its HE tables fail the
  cross-publication check (quarantined; 1399 national values then come from the 1400-1402 books).
* Archives (`.rar`, `.zip`) were listed, not extracted: each contains the same files that sit
  unpacked beside it (checked for 1345, 1386, 1390, 1402 rar and 1353-1379 zip listings).
* Geography: province level only; **no county (شهرستان) tables** in the national yearbook's
  education chapter (county data is in the provincial yearbooks, not in this source)."""


def write_mappings() -> None:
    L = ["# Term mapping (source wording -> normalised dimension)", "",
         "Generated from `etl/terms.py` (`RULES`), also loaded into the `term_map` table. Matching is on",
         "`norm()`-ed text with spaces removed; within a dimension the first matching rule wins, so the",
         "order below is significant. `domain` scopes a rule to K-12 (`k12`) or higher education (`he`);",
         "a table's domain is decided once from its title (`classify_domain`), which is what keeps the",
         "two levels apart. The source wording is kept next to every normalised value (`level_source`,",
         "`degree_level_source`, `row_label`, `col_header`).", "",
         "| # | dim | value | pattern | how | domain | note |", "|---|---|---|---|---|---|---|"]
    for i, r in enumerate(RULES):
        L.append(f"| {i} | {r.dim} | {r.value} | {r.pattern} | {r.how} | {r.domain} | {r.note} |")
    L += ["", "## Normalised K-12 levels", "",
          "| level | meaning | notes |", "|---|---|---|",
          "| preschool | پیش‌دبستانی / آمادگی / کودکستان | 1 year before primary |",
          "| primary | ابتدایی / دبستان | 5 grades until 1390-91, 6 grades from 1391-92 |",
          "| lower_secondary | راهنمایی تحصیلی (old, grades 6-8) / دوره اول متوسطه (new, grades 7-9) | `school_system` column tells which; 1391-1393 is the transition (guidance school phased out) |",
          "| upper_secondary | متوسطه (old, 3 grades, incl. نظری/فنی و حرفه‌ای/کاردانش) / دوره دوم متوسطه (new, grades 10-12) | pre-university became grade 12 in the new system |",
          "| pre_university | پیش‌دانشگاهی | old system only (to ~1397) |",
          "| all_levels | table or row covers all levels | never summed with the per-level rows |",
          "", "`programme` (regular / adult / special_needs) is kept separate from `level`.", "",
          "## Normalised higher-education degree levels", "",
          "| degree_level | Persian | note |", "|---|---|---|",
          "| associate | کاردانی (فوق دیپلم) | |", "| bachelor | کارشناسی (لیسانس) | |",
          "| master | کارشناسی ارشد (فوق لیسانس) | |", "| professional_doctorate | دکترای حرفه‌ای (e.g. MD, DVM, PharmD) | |",
          "| phd | دکترای تخصصی | |", "| doctorate_unspecified | دکترا | older tables that do not split the two |",
          "", "## University types", "",
          "| university_type | Persian | note |", "|---|---|---|",
          "| all_reported | the table's own total | coverage in `coverage` (incl_azad / excl_uast ...) |",
          "| excl_azad | total *excluding* Islamic Azad University | footnote «به استثنای دانشگاه آزاد», yearbooks <= 1392 |",
          "| azad | دانشگاه آزاد اسلامی | |", "| payame_noor | دانشگاه پیام نور | |",
          "| applied_science | دانشگاه جامع علمی-کاربردی (UAST) | |",
          "| technical_vocational_univ | دانشگاه فنی و حرفه‌ای | |",
          "| farhangian_teacher_training | دانشگاه فرهنگیان (teacher-training) | |",
          "| public_msrt | universities of the Ministry of Science (MSRT) | |",
          "| public_mohme | universities of the Ministry of Health (medical) | |",
          "| public_other | other executive bodies | |", "| private_nonprofit | غیردولتی-غیرانتفاعی | |"]
    (DOCS / "mappings.md").write_text("\n".join(L) + "\n")
